// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQM7KYdnczqbFUj02LsQUHHmqsnj1cymY',
    appId: '1:58059013710:web:488f845b1d97d200a8cd1f',
    messagingSenderId: '58059013710',
    projectId: 'auroramusic-7fc25',
    authDomain: 'auroramusic-7fc25.firebaseapp.com',
    storageBucket: 'auroramusic-7fc25.appspot.com',
    measurementId: 'G-G71VWZGHRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4R5yY1wVs2d7NleymHcd6j-uiWOIrvhI',
    appId: '1:58059013710:android:bba9f306591c6160a8cd1f',
    messagingSenderId: '58059013710',
    projectId: 'auroramusic-7fc25',
    storageBucket: 'auroramusic-7fc25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR4uLF6RfYhPcH00wujJPHKc0enY9yIuY',
    appId: '1:58059013710:ios:ea12f70ed3b03a42a8cd1f',
    messagingSenderId: '58059013710',
    projectId: 'auroramusic-7fc25',
    storageBucket: 'auroramusic-7fc25.appspot.com',
    iosBundleId: 'com.example.auroraMusicV01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR4uLF6RfYhPcH00wujJPHKc0enY9yIuY',
    appId: '1:58059013710:ios:ea12f70ed3b03a42a8cd1f',
    messagingSenderId: '58059013710',
    projectId: 'auroramusic-7fc25',
    storageBucket: 'auroramusic-7fc25.appspot.com',
    iosBundleId: 'com.example.auroraMusicV01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQM7KYdnczqbFUj02LsQUHHmqsnj1cymY',
    appId: '1:58059013710:web:08a9aced172799baa8cd1f',
    messagingSenderId: '58059013710',
    projectId: 'auroramusic-7fc25',
    authDomain: 'auroramusic-7fc25.firebaseapp.com',
    storageBucket: 'auroramusic-7fc25.appspot.com',
    measurementId: 'G-96FHPNJ4TK',
  );

  
}